export const cardMapping = {
    "Hercule Poirot": 7,
    "Miss Marple": 8,
    "Mr Sattertwhaite": 9,
    "Parker Pyne": 10,
    "Lady Eileen Brent": 11,
    "Tommy Beresford": 12,
    "Tuppence Beresford": 13,
    "Harley Quin": 14,
    "Ariadne Oliver": 15,
    "Not so Fast!" : 16,
    "Cards off the table": 17,
    "Another Victim": 18,
    "Dead Card Folly": 19,
    "Look in to the Ashes": 20,
    "Card Trade": 21,
    "And There was One More...": 22,
    "Delay the Muderer's Escape": 23,
    "Early Train to Paddington": 24,
    "Point Your Suspicions": 25,
    "Blackmailed!": 26,
    "Social Faux Pas": 27,
  };
  